- name: remove existing directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCAION }}"
    state: absent

- name: create app directory
  tags: 
  - deployment
  ansible.builtin.file:
    path: "{{ APP_LOCAION }}"
    state: directory

- name: Unzip the file
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip"
    dest: "{{ App_location }}"
    remote_src: yes