- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application code
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip
    dest: /tmp/backend.zip

- name: Unzip the file
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: "{{ App_location }}"
    remote_src: yes